[package]
name = "tipping"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tipping"
crate-type = ["cdylib"]

[dependencies]
fancy-regex = "0.13.0"
pyo3 = "0.25.1"
tipping-rs = { path = "../core" }
